export const es = {
  donCalceton: "Don Calcetón",
  store: "Tienda",
  cart: "Carrito",
  products: {
    name: "productos",
    search: "Buscar productos",
    new: "Nuevo producto",
    edit: "Editar producto",
    basePrice: "Precio base: ",
    base: "Base: $",
    wholesalePrice: "Mayoreo: $",
    wholesalePriceLabel: "Precio a mayoreo",
    more: "mas...",
    namePlaceholder: "Playera",
    pricePlaceholder: "150.30",
    wholesalePricePlaceholder: "130",
    description: "Descripción",
    descriptionPlaceholder: "de algodón cuello redondo holgada",
  },
  variants: {
    name: "Variantes",
    search: "Buscar variantes",
    new: "Nueva variante",
    personalizationOptions: "Opciones de personalización",
    images: "Imágenes",
    namePlaceholder: "Playera rosa",
    stock: "Stock",
    stockPlaceholder: "50",
    onlyIntegers: "Solo se pueden guardar valores enteros",
    changeImages: "Cambiar imagenes",
    browseImages: "Elige tus imágenes",
    dragImages: "o arrastralas aquí",
  },
  customizations: {
    new: "Nueva personalización",
    name: "personalizaciones",
    imageMin: "Imagen min:",
    imageMax: "Imagen max:",
    cm: "cm",
    titlePlaceholder: "Esquina superior izquierda",
    minSizePlaceholder: "0",
    maxSizePlaceholder: "20",
  },
  login: {
    email: "Correo",
    emailPlaceholder: "calcetas@mail.com",
    password: "Contraseña",
    passwordPlaceholder: "tu contraseña",
    forgotPassword: "olvidaste tu contraseña?",
    login: "Entrar",
    hidePassword: "Ocultar contraseña",
    showPassword: "Mostrar contraseña",
  },
  changePassword: {
    name: "Cambio de contraseña",
    newPassword: "Nueva contraseña",
    confirmPassword: "Confirma la contraseña",
    forgotPassword: "Olvidaste tu contraseña?",
    writeEmail:
      "Escribe aquí tu correo y enviaremos un mensaje de actualización",
  },
  goToMail: {
    title: "Listo!",
    description:
      "En tu bandeja de correo te dejamos las instrucciones para restablecer tu contraseña",
    toBegining: "Ir al inicio",
  },
  orders: {
    sendSuccess: "Pedido enviado correctamente",
    emptyFields: "Algunos campos están vacíos, por favor revisa tu pedido",
    buy: "Comprar",
    totalPrice: "Precio total $",
    products: "Productos",
    name: "Pedidos",
    order: "Pedido",
    position: "Posición:",
    imageSize: "Tamaño de imagen(es):",
    statusLabel: "Estado de pedido:",
    status: {
      IN_PROCESS: "En proceso",
      DELIVERED: "Entregado",
      CANCELED: "Cancelado",
    },
    downloadImages: "Descargar imágenes",
    transaction:
      "Transacción {status}:{transactionId}. Checa la consola para mas detalles",
    shipping: {
      toAddress: "Envio a domicilio",
    },
  },
  unsavedChangesModal: {
    title: "Cambios sin guardar",
    description: "Si sales ahora, se perderán todos los cambios",
    return: "Regresar",
    continue: "Continuar",
  },
  paypal: {
    softDescriptor: "calceton",
  },
  errors: {
    stock: "No hay suficiente stock",
    updateOrder: "Hubo un error al intentar guardar el nuevo metodo de envio",
    address:
      "Lamentablemente no contamos con envios a tu dirección, por favor elige una dirección diferente",
    generic: "Hubo un error, por favor intenta de nuevo",
  },
  name: "Nombre",
  cancel: "Cancelar",
  save: "Guardar",
  send: "Enviar",
  priceSymbol: "$",
  mxn: "MXN",
  search: "Buscar",
  stock: "stock:",
  imagesPngJpg: "Imagenes (PNG, JPG)",
  filterByProduct: "Filtrar por producto",
  add: "Agregar",
  loading: "Cargando...",
};
