export const es = {
  donCalceton: "Don Calcetón",
  store: "Tienda",
  cart: "Carrito",
  products: {
    name: "productos",
    search: "Buscar productos",
    new: "Nuevo producto",
    edit: "Editar producto",
    basePrice: "Precio base: ",
    base: "Base: $",
    wholesalePrice: "Mayoreo: $",
    wholesalePriceLabel: "Precio a mayoreo",
    more: "mas...",
    namePlaceholder: "Playera",
    pricePlaceholder: "150.30",
    wholesalePricePlaceholder: "130",
    description: "Descripción",
    descriptionPlaceholder: "de algodón cuello redondo holgada",
  },
  variants: {
    name: "Variantes",
    search: "Buscar variantes",
    new: "Nueva variante",
    personalizationOptions: "Opciones de personalización",
    images: "Imágenes",
    namePlaceholder: "Playera rosa",
    stock: "Stock",
    stockPlaceholder: "50",
    onlyIntegers: "Solo se pueden guardar valores enteros",
  },
  customizations: {
    new: "Nueva personalización",
    name: "personalizaciones",
    imageMin: "Imagen min:",
    imageMax: "Imagen max:",
    cm: "cm",
    titlePlaceholder: "Esquina superior izquierda",
  },
  login: {
    email: "Correo",
    emailPlaceholder: "calcetas@mail.com",
    password: "Contraseña",
    passwordPlaceholder: "tu contraseña",
    forgotPassword: "olvidaste tu contraseña?",
    login: "Entrar",
    hidePassword: "Ocultar contraseña",
    showPassword: "Mostrar contraseña",
  },
  changePassword: {
    name: "Cambio de contraseña",
    newPassword: "Nueva contraseña",
    confirmPassword: "Confirma la contraseña",
    forgotPassword: "Olvidaste tu contraseña?",
    writeEmail:
      "Escribe aquí tu correo y enviaremos un mensaje de actualización",
  },
  goToMail: {
    title: "Listo!",
    description:
      "En tu bandeja de correo te dejamos las instrucciones para restablecer tu contraseña",
    toBegining: "Ir al inicio",
  },
  orders: {
    sendSuccess: "Pedido enviado correctamente",
    emptyFields: "Algunos campos están vacíos, por favor revisa tu pedido",
  },
  name: "Nombre",
  cancel: "Cancelar",
  save: "Guardar",
  send: "Enviar",
  priceSymbol: "$",
  mxn: "MXN",
  search: "Buscar",
  stock: "stock:",
  imagesPngJpg: "Imagenes (PNG, JPG)",
  filterByProduct: "Filtrar por producto",
  add: "Agregar",
  loading: "Cargando...",
};
